[build-system]
requires = ["setuptools >= 67.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/"]
include = ["sdh.table"]

[project]
name = "sdh.table"
description = "Table rendering engine."
version = "2.3.0"
dependencies = [
  "Django>=3.2"
]
requires-python = ">= 3.8"
license = {file = 'LICENSE'}

authors = [
    {name = "Viacheslav Vic Bukhantsov", email = "vic.bukhantsov@gmail.com"},
    {name = "Andriy Koziy", email="andriy@koziy.com"},
    {name = "Oleg Koziy", email="olekhelk@gmail.com"},
    {name = "Pavel Yablonskiy", email="yapple@ua2crm.com"},
    {name = "Borys Vorona", email="borysvorona@gmail.com"},
]

maintainers = [
  {name = "Viacheslav Vic Bukhantsov", email = "vic.bukhantsov@gmail.com"}
]

classifiers = [
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules',
]

[project.urls]
Repository = "https://github.com/sdh-global/sdh-table"
