# Generated by Django 4.2.21 on 2025-08-12 04:04

from django.db import migrations, models


def handle_duplicate_defaults(apps, schema_editor):
    """
    For each (user, tableview_name) combination, keep only the first record with is_default=True
    and set is_default=False for all other duplicate records.
    """
    TableViewProfile = apps.get_model('table', 'TableViewProfile')

    # Get all unique (user, tableview_name) combinations that have is_default=True
    user_tableview_combinations = TableViewProfile.objects.filter(
        is_default=True
    ).values('user', 'tableview_name').distinct()

    for combo in user_tableview_combinations:
        user_id = combo['user']
        tableview_name = combo['tableview_name']

        # Get all records for this user+tableview_name with is_default=True, ordered by id
        user_tableview_defaults = TableViewProfile.objects.filter(
            user=user_id,
            tableview_name=tableview_name,
            is_default=True
        ).order_by('id')

        # Keep the first one, set is_default=False for the rest
        if user_tableview_defaults.count() > 1:
            first_record = user_tableview_defaults.first()
            # Set is_default=False for all except the first
            user_tableview_defaults.exclude(id=first_record.id).update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            handle_duplicate_defaults,
        ),
    ]
