# Generated by Django 4.2.21 on 2025-08-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0002_tableviewprofile"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tableviewprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "tableview_name"),
                condition=models.Q(is_default=True),
                name="unique_default_per_user_tableview"
            ),
        ),
    ]
